# Site settings
title: I like to get things done
email: jasonmgainor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Jason Gainor
email: jasonmgainor@gmail.com
facebook_username:
twitter_username:
github_username: jasongainor
address: 
line: 
line: 
  # Feel free to add more lines here
telephone: +1(781)777-3140
copyright:

# API settings
google_api_key: AIzaSyB6sddwTgmGemTiOz01pZdl8mq-WxTaxZ8

# Build settings
markdown: kramdown
